services:
  trim:
    build:
      context: .
      args:
        - CORE_GZ=core.gz
        - ITERATION_NUMBER=1
        - KERNEL_BRANCH=v6.x
        - KERNEL_SUFFIX=tinycore-560z
        - KERNEL_VERSION=6.1.2
        - TCL_MAJOR_VERSION_NUMBER=14
        - TCL_RELEASE_TYPE=release
        - TCL_VERSION=14.x
      tags:
        - linichotmailca/tcl-core-560z-trim:6.1.2.14.1
        - linichotmailca/tcl-core-560z-trim:latest
      dockerfile: Dockerfile.trim

